import tseslint from 'typescript-eslint'

export default [
  {
    ignores: ['dist/**', 'node_modules/**', 'storybook-static/**', 'test-output/**'],
  },
  {
    files: [
      '*.js',
      '*.mjs',
      'scripts/**/*.mjs',
      'tests/**/*.js',
      'tests/**/*.mjs',
    ],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        BroadcastChannel: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        Headers: 'readonly',
        Map: 'readonly',
        Promise: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        ResizeObserver: 'readonly',
        Set: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        caches: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        indexedDB: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      curly: ['error', 'all'],
      eqeqeq: ['error', 'always'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
    },
  },
  ...tseslint.configs.recommended.map((config) => ({
    ...config,
    files: [
      'src/**/*.{ts,tsx}',
      'shared/**/*.ts',
      'tests/e2e/**/*.ts',
      'tests/unit/react-*/**/*.{ts,tsx}',
      'tests/unit/scripts/**/*.js',
      'tests/unit/shared/**/*.ts',
      '.storybook/**/*.{ts,tsx}',
      'vite.config.js',
      'vitest.config.ts',
      'vitest.storybook.config.ts',
      'playwright.config.js',
      'playwright.visual.config.js',
    ],
  })),
]
